---
title: "Lab 9 Sequence Alignment"
author: "Kaleigh Weeks"
format:
  html:
    toc: true
    toc_float: true
    embed-resources: true
    theme: cosmos
execute: 
  warning: false
  message: false
---

# Lab 9

```{r}
#| eval: false
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.21")
```

```{r}
#| eval: false
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ggtree")
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biostrings")
```

The ggtree package

```{r}
# You may need to install the treeio, rphylopic and ggimage packages
library(tidyverse)
library(ggtree)
library(treeio)
library(rphylopic)
library(ggimage)
```

Basic Trees code chunks

```{r}
tree <- read.tree("/work/pi_bio678_umass_edu/data/lab13/tree_newick.nwk")
tree
```

```{r}
# build a ggplot with a geom_tree
ggplot(tree) + geom_tree() + theme_tree()
# This is convenient shorthand
ggtree(tree)
```

```{r}
# add a scale
ggtree(tree) + geom_treescale()
# or add the entire scale to the x axis with theme_tree2()
ggtree(tree) + theme_tree2()
```

```{r}
ggtree(tree, branch.length="none")
```

```{r}
ggtree(tree, branch.length="none", color="blue", size=2, linetype=3)
```

Exercise 1

```{r}
library(ggtree)
library(ape)

# Example tree
tree <- rtree(10)

# Slanted layout
ggtree(tree, layout = "slanted")

```

```{r}
ggtree(tree, layout = "circular")

```

```{r}
ggtree(tree, layout = "circular", branch.length = "none") +
  geom_tree(color = "red", size = 2)

```

Other tree geoms code chunk

```{r}
# create the basic plot
p <- ggtree(tree)
# add node points
p + geom_nodepoint()
# add tip points
p + geom_tippoint()
# Label the tips
p + geom_tiplab()
```

Exercise 2

```{r}
library(ggtree)
library(ape)

# Generate a random tree with 10 tips
tree <- rtree(10)

# Replace tip labels with letters A–J
tree$tip.label <- LETTERS[1:10]

# Create the customized plot
ggtree(tree) +
  geom_tiplab(color = "purple") +                                      # Tips labeled in purple
  geom_tippoint(color = "purple", shape = 23, fill = "purple", size = 1.5) +  # Diamond-shaped purple tip points
  geom_nodepoint(color = "yellow", size = 6, alpha = 0.5) +            # Large semitransparent yellow node points
  ggtitle("Phylogenetic Tree with Lettered Tips")

```

Tree annotation code chunks

```{r}
ggtree(tree) + geom_text(aes(label=node), hjust=-.3)
```

```{r}
ggtree(tree) + geom_tiplab()
```

```{r}
MRCA(tree, c("C", "E"))
```

```{r}
MRCA(tree, c("G", "H"))
```

```{r}
# MRCA(tree, tip=c("C", "E"))
# MRCA(tree, tip=c("G", "H"))
```

Labeling clades code chunks

```{r}
ggtree(tree) + 
  geom_cladelabel(node=17, label="Some random clade", color="red")
```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.03)
```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.03) + 
  geom_cladelabel(node=21, label="A different clade", 
                  color="blue", offset=.8)
```

```{r}
library(ggtree)
library(ape)

# Generate a random tree with 10 tips
tree <- rtree(10)
tree$tip.label <- LETTERS[1:10]  # Label tips with letters A–J

# Plot the tree
ggtree(tree) +
  geom_tiplab(color = "purple", size = 4) +  # Larger purple tip labels
  geom_cladelabel(node = 17, label = "Some random clade", 
                  color = "red2", offset = 1.5, align = TRUE, fontsize = 5) +
  geom_cladelabel(node = 21, label = "A different clade", 
                  color = "blue", offset = 1.5, align = TRUE, fontsize = 5) +
  theme_tree2() + 
  xlim(0, 10) +  # Manually increase this value if labels are still cut off
  ggtitle("Wider Phylogenetic Tree with Clade Labels")

```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_hilight(node=17, fill="gold") + 
  geom_hilight(node=19, fill="purple")
```

Connecting taxa code chunks

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_taxalink("E", "H", color="blue3") +
  geom_taxalink("C", "G", color="orange2", curvature=-.9)
```

Exercise 3

```{r}
ggtree(tree) +
  geom_tiplab() +
  
  # Highlight clades
  geom_hilight(node = 15, fill = "orange", alpha = 0.5) +  # B+C
  geom_hilight(node = 22, fill = "purple", alpha = 0.5) +   # L+J
  
  # Label the superclade
  geom_cladelabel(node = 17, label = "Superclade A–E", color = "red", offset = 0.002, fontsize = 2, align = TRUE) +
  
  # Dashed gray links using data frame
  geom_taxalink(data = data.frame(taxa1 = c("C", "G"), taxa2 = c("E", "J")),
                aes(taxa1 = taxa1, taxa2 = taxa2),
                color = "gray", linetype = 2) +
  
  # Add scale bar and title
  theme_tree2() +
  ggtitle("Exercise 3 title: Not sure what we're trying to show here...")

```

Bonus code chunks

```{r}
set.seed(42)
trees <- lapply(rep(c(10, 25, 50, 100), 3), rtree)
class(trees) <- "multiPhylo"
ggtree(trees) + facet_wrap(~.id, scale="free", ncol=4) + ggtitle("Many trees. Such phylogenetics. Wow.")
```

Plotting trees with other data

```{r}
# Generate a random tree with 30 tips
tree <- rtree(30)
# Make the original plot
p <- ggtree(tree)
# generate some random values for each tip label in the data
d1 <- data.frame(id=tree$tip.label, val=rnorm(30, sd=3))
# Make a second plot with the original, naming the new plot "dot", 
# using the data you just created, with a point geom.
p2 <- facet_plot(p, panel="dot", data=d1, geom=geom_point, aes(x=val), color='red3')
# Make some more data with another random value.
d2 <- data.frame(id=tree$tip.label, value = abs(rnorm(30, mean=100, sd=50)))
# Now add to that second plot, this time using the new d2 data above, 
# This time showing a bar segment, size 3, colored blue.
p3 <- facet_plot(p2, panel='bar', data=d2, geom=geom_segment, 
           aes(x=0, xend=value, y=y, yend=y), size=3, color='blue4') 
# Show all three plots with a scale
p3 + theme_tree2()
```

Overlay organism silouhettes

```{r}
# get phylopic 

newick <- "((Pongo_abelii,(Gorilla_gorilla_gorilla,(Pan_paniscus,Pan_troglodytes)Pan,Homo_sapiens)Homininae)Hominidae,Nomascus_leucogenys)Hominoidea;"

tree <- read.tree(text=newick)

d <- ggimage::phylopic_uid(tree$tip.label)
d$body_mass = c(52, 114, 47, 45, 58, 6)

p <- ggtree(tree) %<+% d + 
  geom_tiplab(aes(image=uid, colour=body_mass), geom="phylopic", offset=3.2) +
  geom_tiplab(aes(label=label), offset = .2) + xlim(NA, 7) +
  scale_color_viridis_c()
p  
```

Tips

```{r}
# Add to your 
ggtree(tree) +
  xlim(0,4) # This worked from my rectangular trees
  xlim(0, 6) # This worked for my circular trees
```

```{r}
ggtree(tree) +  
  geom_nodelab()
```

```{r}
ggtree(tree) +
  geom_tiplab(hjust=-.1, size = 3)
```

```{r}
ggtree(tree) +
  geom_hilight(node=4, fill="gold", extend = 0.5) 
```
